version: '3.3'
services:
    httpd:
        ports:
            - '80:80'
        container_name: website-apache
        volumes:
            - './apache-ngnix:/usr/local/apache2/htdocs:ro'
        image: httpd